### ISSUE TITLE
Unexpected error fetching config data: data type mismatch

### ISSUE THREAD

**Issue by nicolasmai** [siku2/hass-vzug#46]
I get this error for while initializing:
AdoraDry V2000
AdoraWash V2000
Combair V600

2024-04-06 09:25:12.780 ERROR (MainThread) [custom_components.vzug.shared] Unexpected error fetching config data: data type mismatch (<class 'NoneType'> != <class 'list'>)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/shared.py", line 147, in _fetch_config
    return await self.client.aggregate_config()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 274, in aggregate_config
    category_keys = await self.list_categories()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 354, in list_categories
    return await self._command(
           ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 233, in _command
    raise last_exc
  File "/config/custom_components/vzug/api.py", line 219, in _command
    return await once()
           ^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 209, in once
    assert isinstance(
AssertionError: data type mismatch (<class 'NoneType'> != <class 'list'>)

It works for two other devices:
AdoraDish V2000
CombiCooler V4000

**Comment by nicolasmai** [comment]
works with the latest alpha

**Comment by nicolasmai** [comment]
works with the latest alpha

**Comment by nicolasmai** [comment]
works with the latest alpha
