### ISSUE TITLE
CombiMiwell V4000 45 fails to setup

### ISSUE THREAD

**Issue by thomasknuchel** [siku2/hass-vzug#50]
My CombiMiwell V4000 45 cannot be setup anymore (past there was no issue).
Failed setup, will retry: Unexpected end of data: ilne 9 column 22 (char 605).

Logger: custom_components.vzug.shared
Source: helpers/update_coordinator.py:312
integration: V-ZUG ([documentation](https://github.com/siku2/hass-vzug), [issues](https://github.com/siku2/hass-vzug/issues))
First occurred: 16:25:14 (1 occurrences)
Last logged: 16:25:14

Unexpected error fetching state data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/shared.py", line 132, in _fetch_state
    return await self.client.aggregate_state(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 246, in aggregate_state
    notifications=await self.get_last_push_notifications(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 345, in get_last_push_notifications
    return await self._command(
           ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 219, in _command
    return await once()
           ^^^^^^^^^^^^
  File "/config/custom_components/vzug/api.py", line 206, in once
    data = await resp.json(content_type=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 79, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1192, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 48, in json_loads
    return orjson.loads(__obj)  # type:ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected end of data: line 9 column 22 (char 605)

**Comment by david-aggeler** [comment]
@thomasknuchel , can you try 0.4.5? Another user also had JSON deserialzation issues and tried 0.4.5 succesfully. See [https://github.com/siku2/hass-vzug/issues/112](url). 

If not, Any chance you can get the result of http://ip-or-hostname/ai?command=getLastPUSHNotifications with a browser or postman?
